import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import styles from "./page.module.scss";
import "../assets/styles/main.scss";
import "./globals.css";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <span className={styles.Scroll} id="root"></span>
                <Navbar />
                <div className={styles.Background}>
                    <div className={styles.Background__BtnBg} />
                    <div className={styles.Background__Fade} />
                </div>
                <div className={styles.Content}>{children}</div>
                <Footer />
            </body>
        </html>
    );
}
