import "./globals.css";
import "../assets/styles/main.scss";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import styles from "./page.module.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className={styles.Background}>
          <div className={styles.Background__BtnBg} />
          <div className={styles.Background__Fade} />
        </div>
        <div className={styles.Content}>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
